# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v1
kind: Config
profiles:
  #for remote builds
  - name: gcb
    build:
      googleCloudBuild:
        diskSizeGb: 10
        machineType: N1_HIGHCPU_8
        timeout: 1200s
  # dev skaffold profile will build and push images to dev project
  - name: dev
    build:
      googleCloudBuild:
        diskSizeGb: 10
        machineType: N1_HIGHCPU_8
        timeout: 1200s
      artifacts:
      - image: frontend
        context: ./frontend/
      - image: profileservice
        context: ./profileservice/
      - image: transferservice
        context: ./transferservice/
        docker:
          dockerfile: Dockerfile-prod
      - image: transactionservice
        context: ./transactionservice/
        docker:
          dockerfile: Dockerfile-prod
      - image: loadgen
        context: ./e2e-loadtest/
  # prod skaffold profile will build and push images to prod project
  - name: prod
    build:
      artifacts:
      - image: frontend
        context: ./frontend/
      - image: profileservice
        context: ./profileservice/
      - image: transferservice
        context: ./transferservice/
        docker:
          dockerfile: Dockerfile-prod
      - image: transactionservice
        context: ./transactionservice/
        docker:
          dockerfile: Dockerfile-prod
      - image: loadgen
        context: ./e2e-loadtest/
    
