apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-app-hpa
  namespace: fsi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
