apiVersion: v1
kind: Service
metadata:
  name: transaction-app-svc
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: transaction-app
  ports:
  - name: http
    port: 5050
    targetPort: 5050