apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: transaction-vs
  namespace: fsi
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway
  http:
  - match:
    - uri:
        prefix: /api/transaction
    route:
    - destination:
        host: transaction-app-svc
        port:
          number: 5050